# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/documentation',
                'doc_host': 'https://burvall.github.io',
                'git_url': 'https://github.com/burvall/documentation',
                'lib_path': 'documentation'},
  'syms': {'documentation.core': {'documentation.core.foo': ('core.html#foo', 'documentation/core.py')}}}